### PR TITLE
Updated color scheme for municipalities/regions 

### PR DESCRIPTION
**Pull request by sebastjancizel**
Implemented a new color scheme for municipalities and regions maps, based on the colors from World map. This is in reference to #582. 

Note:
- The chart showing numbers of deceased in now also in the same color scheme as opposed to greyscale before (revert to greyscale?)

Let me know if I can improve it in any way.

Screen Shot 2020-10-12 at 10 01 13 AM
Screen Shot 2020-10-12 at 10 01 43 AM
Screen Shot 2020-10-12 at 10 03 56 AM
Screen Shot 2020-10-12 at 10 04 16 AM

### CODE REVIEW

**Comment by mkadunc** [comment]
I would be most interested in the "Relative" display, which was the most problematic in the old version. Could you share a screenshot of that as well?

**Comment by mkadunc** [comment]
For deceased, i'd prefer a non-gray scheme, e.g. purple https://colorbrewer2.org/#type=sequential&scheme=Purples&n=9

**Comment by sebastjancizel** [comment]
I see, I wasn't paying enough attention to the relative charts. They look fine for daily values:
Screen Shot 2020-10-12 at 2 54 39 PM
But become very problematic in particular for the region map with longer time scales e.g.:
Screen Shot 2020-10-12 at 2 55 55 PM
I'll get on with fixing that. 

Meanwhile I have implemented the purple color scheme for deceased. Here's a snapshot:
Screen Shot 2020-10-12 at 2 56 31 PM

**Comment by mkadunc** [comment]
It's hard to see from the screenshots — is the color scale logarithmic (1 / 2 / 4 / 8 / 16 / 32) or linear (0 / 7 / 14 / 21 / 28 / 35) ?

We discussed that logarithmic would be best, in all cases (absolute & relative).

**Comment by sebastjancizel** [comment]
> It's hard to see from the screenshots — is the color scale logarithmic (1 / 2 / 4 / 8 / 16 / 32) or linear (0 / 7 / 14 / 21 / 28 / 35) ?
> 
> We discussed that logarithmic would be best, in all cases (absolute & relative).

Aaa I didn't realize that! (sorry about that, I'm new) Thanks for pointing that out! I'll change that.

**Comment by lukarenko** [comment]
@sebastjancizel sem ti dal Write pravice na projektu - zdaj lahko narediš branch iz master in potem tam lahko naredimo deploy-preview, da bodo tudi ostali lahko testirali tvojo testno verzijo.

**Pull request closed without merging**
