### PR TITLE
Optional query params, meta tags

### PR DESCRIPTION
**Pull request by miaerbus**
For testing purposes, an optional query param _showDate_ was added to show data for the specific date: https://pr-344.sledilnik.org/sl/stats?showDate=2020-05-07

Additionally, REST API completely replaced CSV for the front page. Only tables page still uses CSV.

### CODE REVIEW

**Comment by miaerbus** [comment]
With the last commit, I fixed the html lang and meta title tag. If someone wants to check why other meta tags are not changing when switching the language, feel free to chip in. Here is the documentation: https://vue-meta.nuxtjs.org/api/#meta (btw, I really like how the url is dynamically changing as you scroll up and down on this page - maybe we could have this too)

**Comment by stefanb** [comment]
💡Other meta info tags are possibly not changing because they are not translated in en.json yet

**Comment by stefanb** [comment]
> 💡Other meta info tags are possibly not changing because they are not translated in en.json yet

Ah, scratch that - the whole en.json got reformatted, diff too large and hidden by github when reviewing

**Comment by stefanb** [comment]
<title< tag gets replaced nicely, but other meta tags just gets added to DOM, ending up with 2 of each:
image

```html
<meta name="description" content="COVID-19 Sledilnik Slovenija - zbrani, preverjeni, ažurirani, analizirani in pregledni podatki o epidemiji COVID-19 v Sloveniji. | COVID-19 Slovenia Tracking - collected, verified, updated, analyzed and reviewed COVID-19 data for Slovenia (preview)">

<meta data-vue-meta="1" name="description" content="COVID-19 Slovenia Tracking - collected, verified, updated, analyzed and reviewed COVID-19 data for Slovenia.">
```
same for `twitter:title`, `twitter:description`...

Removing them from `index.html` and `index_caddy.html` could help, but there could be other ways to do so.

**Comment by stefanb** [comment]
Sadly, many sites seem to rely on static html in the html...
- https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fpr-344.sledilnik.org%2Fen%2Fstats
- https://opengraphcheck.com/result.php?url=https%3A%2F%2Fpr-344.sledilnik.org%2Fen%2Fstats
- https://cards-dev.twitter.com/validator (enter https://pr-344.sledilnik.org/en/stats )

...so we'd need some default static and then remove those tags from DOM when rendering localized content.

**Pull request merged**
