### PR TITLE
Use youtube-nocookie.com domain to make 3rd party tracking harder

### PR DESCRIPTION
**Pull request by stefanb**
Please test at https://pr-717.sledilnik.org/sl/stats#youtube

### CODE REVIEW

**Comment by miaerbus** [comment]
I recently removed the "youtube-nocookie.com" domain because there were some console errors. Could you maybe check how to resolve these issues? Otherwise I completely support this domain 👍

**Comment by stefanb** [comment]
Tnx @miaerbus!
Do you remember what the errors were or in what browser they occurred? I see nothing unusual.

**Comment by miaerbus** [comment]
Screenshot 2020-11-27 at 08 46 51

I get this error in Chrome, Firefox, Safari. If it's not an important error, just merge :)

**Comment by stefanb** [comment]
Those errors seem to be some ads or tracking failing, not any important video functionality.

**Pull request merged**
